Repository mlabs-haskell/lambda-buffers, pull requests merged in 2023-11, with the labels that each got.

#135 Upgrading to CTL latest
  extras/flake-purescript.nix
  flake.lock
  flake.nix
  lambda-buffers-codegen/data/purescript-prelude-base.json
  lambda-buffers-codegen/src/LambdaBuffers/Codegen/Purescript/Print/LamVal.hs
  runtimes/purescript/lbr-plutus/build.nix
  runtimes/purescript/lbr-plutus/esbuild/bundle.js
  runtimes/purescript/lbr-plutus/package-lock.json
  runtimes/purescript/lbr-plutus/package.json
  runtimes/purescript/lbr-plutus/packages.dhall
  runtimes/purescript/lbr-plutus/spago-packages.nix
  runtimes/purescript/lbr-plutus/spago.dhall
  runtimes/purescript/lbr-plutus/src/LambdaBuffers/Runtime/Plutus.purs
  runtimes/purescript/lbr-plutus/src/Test/LambdaBuffers/Plutus/Generators/Correct.purs
  runtimes/purescript/lbr-plutus/webpack.config.cjs
  runtimes/purescript/lbr-prelude/build.nix
  runtimes/purescript/lbr-prelude/esbuild/bundle.js
  runtimes/purescript/lbr-prelude/package-lock.json
  runtimes/purescript/lbr-prelude/package.json
  runtimes/purescript/lbr-prelude/packages.dhall
  runtimes/purescript/lbr-prelude/spago-packages.nix
  runtimes/purescript/lbr-prelude/spago.dhall
  runtimes/purescript/lbr-prelude/src/LambdaBuffers/Runtime/Prelude.purs
  runtimes/purescript/lbr-prelude/src/LambdaBuffers/Runtime/Prelude/Generators/Correct.purs
  runtimes/purescript/lbr-prelude/src/LambdaBuffers/Runtime/Prelude/Json.purs
  runtimes/purescript/lbr-prelude/webpack.config.cjs
  testsuites/lbt-plutus/lbt-plutus-purescript/build.nix
  testsuites/lbt-plutus/lbt-plutus-purescript/esbuild/bundle.js
  testsuites/lbt-plutus/lbt-plutus-purescript/package-lock.json
  testsuites/lbt-plutus/lbt-plutus-purescript/package.json
  testsuites/lbt-plutus/lbt-plutus-purescript/packages.dhall
  testsuites/lbt-plutus/lbt-plutus-purescript/spago-packages.nix
  testsuites/lbt-plutus/lbt-plutus-purescript/spago.dhall
  testsuites/lbt-plutus/lbt-plutus-purescript/test/Test/LambdaBuffers/Runtime/Plutus/Generators/Correct.purs
  testsuites/lbt-plutus/lbt-plutus-purescript/webpack.config.cjs
  testsuites/lbt-prelude/lbt-prelude-purescript/build.nix
  testsuites/lbt-prelude/lbt-prelude-purescript/esbuild/bundle.js
  testsuites/lbt-prelude/lbt-prelude-purescript/package-lock.json
  testsuites/lbt-prelude/lbt-prelude-purescript/package.json
  testsuites/lbt-prelude/lbt-prelude-purescript/packages.dhall
  testsuites/lbt-prelude/lbt-prelude-purescript/spago-packages.nix
  testsuites/lbt-prelude/lbt-prelude-purescript/spago.dhall
  testsuites/lbt-prelude/lbt-prelude-purescript/test/Test/LambdaBuffers/Prelude/Golden.purs
  testsuites/lbt-prelude/lbt-prelude-purescript/test/Test/Main.purs
  testsuites/lbt-prelude/lbt-prelude-purescript/webpack.config.cjs
Labels: dependencies, ctl

#137 Selectively updates flake inputs
  flake.lock
  flake.nix
  lambda-buffers-frontend/data/run.sh
Labels: devops

#138 Demo: Expose lbf-nix for users
  docs/plutarch/build.nix
  extras/build.nix
  extras/flake-haskell-plutus.nix
  extras/flake-haskell.nix
  extras/haskell.nix/extra-hackage.nix
  extras/haskell.nix/plutus.nix
  extras/lbf-nix/build.nix
  flake.lock
  flake.nix
  lambda-buffers-codegen/build.nix
  lambda-buffers-compiler/build.nix
  lambda-buffers-frontend/build.nix
  libs/build.nix
  runtimes/haskell/lbr-plutarch/build.nix
  runtimes/haskell/lbr-plutus/build.nix
  runtimes/haskell/lbr-prelude/build.nix
  runtimes/purescript/lbr-plutus/build.nix
  runtimes/purescript/lbr-prelude/build.nix
  runtimes/rust/lbr-prelude-derive/build.nix
  runtimes/rust/lbr-prelude/build.nix
  testsuites/lbt-plutus/api/build.nix
  testsuites/lbt-plutus/golden/build.nix
  testsuites/lbt-plutus/lbt-plutus-haskell/build.nix
  testsuites/lbt-plutus/lbt-plutus-plutarch/build.nix
  testsuites/lbt-plutus/lbt-plutus-purescript/build.nix
  testsuites/lbt-prelude/api/build.nix
  testsuites/lbt-prelude/golden/build.nix
  testsuites/lbt-prelude/lbt-prelude-haskell/build.nix
  testsuites/lbt-prelude/lbt-prelude-purescript/build.nix
Labels: devops

#145 Enables devShellHook and devShellTools in rustFlake and removes system
  extras/flake-rust.nix
  runtimes/rust/lbr-prelude-derive/build.nix
  runtimes/rust/lbr-prelude/build.nix
Labels: enhancement, devops, rust

#149 Add simple Emacs mode
  extras/editor/emacs/lambda-buffers-mode.el
Labels: enhancement, ux

#147 Aligns error reporting with the GNU standard
  lambda-buffers-codegen/app/LambdaBuffers/Codegen/Cli/Gen.hs
  lambda-buffers-codegen/app/LambdaBuffers/Codegen/Cli/GenHaskell.hs
  lambda-buffers-codegen/app/LambdaBuffers/Codegen/Cli/GenPlutarch.hs
  lambda-buffers-codegen/app/LambdaBuffers/Codegen/Cli/GenPurescript.hs
  lambda-buffers-compiler/app/LambdaBuffers/Compiler/Cli/Compile.hs
  lambda-buffers-frontend/app/LambdaBuffers/Frontend/Cli/Build.hs
  lambda-buffers-frontend/app/LambdaBuffers/Frontend/Cli/Env.hs
  lambda-buffers-frontend/app/LambdaBuffers/Frontend/Cli/Utils.hs
  lambda-buffers-frontend/src/LambdaBuffers/Frontend/Errors/Frontend.hs
  lambda-buffers-frontend/src/LambdaBuffers/Frontend/PPrint.hs
  lambda-buffers-frontend/test/Test/LambdaBuffers/Frontend.hs
Labels: enhancement, frontend, ux
